### ISSUE TITLE
PL1-Plantilla de Minutas 

### ISSUE THREAD

**Issue by JoseCarlosPa** [Taro-IT/docs#10]

**Comment by JoseCarlosPa** [comment]
Se sube la plantilla para las minutas

[TARO - numero_minuta titulo_minuta - fecha_minuta (plantilla).docx](https://github.com/Taro-IT/docs/files/7085229/TARO.-.numero_minuta.titulo_minuta.-.fecha_minuta.plantilla.docx)

**Comment by karlaromerox3** [comment]
El campo de "Con copia para" ¿cómo se usaría? De ser que no lo usemos, ¿podría eliminarse? 
Los demás campos de la minuta me parecen muy bien.

**Comment by dinnos** [comment]
Concuerdo con @karlaromerox3 , el punto 1.9 debería ser opcional y solo considerarlo cuando la junta se realizo con participantes externos, en otras palabras; juntas con los Stakeholders para poder compartirla con ellos y tenerlo como evidencia, adicionalmente agregaría una parte en la qué se firme para constar que se esta de acuerdo con los compromisos y desiciones tomadas.
