### ISSUE TITLE
P01-Proceso de juntas departamentales

### ISSUE THREAD

**Issue by EricBL3** [Taro-IT/docs#3]

**Comment by JoseCarlosPa** [comment]
**Propuesta para proceso de "Juntas Departamentales"**

## Objetivo
**Principal:** Eficientar los tiempos y toma de decisiones en temas de relevancia-valor antes y durante las juntas ( Usar la [Plantilla](url) para tener una base establecida y cumplir con los parámetros del proceso).

**Secundario:** Mejorar la precepción de avance y organización dentro de los integrantes del departamento durante todo el semestre para tener  una mejor certeza dela dirección a la que el departamento desea llegar.


## Pre-requisitos

Contar con las plantilla:
- [Juntas departamentales](url)
- [Minutas](url)


## Procedimiento
| Paso|   Descripción   | Área(s) involucradas |
|------|:---------------:|--------------------|
| Notificación    | <ol align="left"><li>Se deberá agendar con anticipación (1 día como mínimo) el horario y fecha de la junta , en caso de tratarse de una junta de emergencia seguir el proceso de  [Juntas de emergencia](url) .</li><li>Para hacer la petición de una junta departamental es recomienda hacerlo a través de un servicio de mensajería instantánea, en este caso es recomendable usar  el canal de SLACK #taro-general con el comando @canal para forzar la notificación a todos los integrantes</li></ol>  | PP |
| Formalización    | Crear un evento en el calendario virtual en este caso se recomienda el uso de Google Calendar siguiendo la [Guía para agendar un evento](url) , de tal modo que le llegue una invitación a todos los interesados. | PP |
| Previo a la junta     | Generar una [Minuta]() la cual deberá estar en la carpeta correspondiente a las Minutas con la siguiente estructura _TARO - numero_de_minuta titulo_minuta - fecha_de_la_minuta_  Ejemplo: TARO - 003 Alcances Inicial - 2021-08-30. Ésta deberá tener asignado un responsable correspondiente al plan de junta. Dentro de esta plantilla se encuentran las siguientes secciones:  <ul align="left"> <li><u>  Control de versión: </li></u> La versión en la que se encuentra la plantilla de la minuta.  <li><u>  Control de versión del documento:  </li></u> En caso de existir modificaciones a la minuta posteriores a su subida, se especifica quien y cuando modifico la minuta.  <li><u> Asunto: </li></u> Se especifica las razones y objetivos de la junta. <li><u>Promotor de la Reunión:  </li></u> Se especifica quien solicito la Reunión. <li><u>  Datos de la Reunión:  </li></u>Se especifica la fecha, hora de inicio, hora de finalización y lugar en la que se realizo la junta.<li><u> Autor de la Minuta:  </li></u>Se especifica quien estuvo editando la minuta.<li><u> Lista de Participantes:  </li></u>Se anota quien pudo asistir a la junta.<li><u>Lista de acuerdos anteriores.</li></u>Se tocan los temas y acuerdos que quedaron pendientes ya sean de revisar o por discutir. <li><u> Agenda:  </li></u>El itinerario con el tiempo aproximado que se dedicara a cada punto.<li><u> Compromisos </li></u>Se formaliza que en que acuerdos se llegaron durante la Reunión especificando, la decisión, el responsable y la fecha de seguimiento.<li><u> Próxima Junta:  </li></u>En caso de existir o agendar otra junta, se especifica la fecha, hora asunto y lugar </ul>  | PP |
| Documentos| Los archivos generados, el plan de junta, la minuta, y la grabación, se subirán la unidad del departamento en la carpeta correspondiente. El nombre de la carpeta nueva debe de tener la estructura siguiente: Número_Tema_Fecha. Ejemplo: 1_Requisitos_iniciales_23ene2019. El nombre de los documentos debe de tener fecha y ser identificados con la estructura siguiente: Archivo_Fecha. Ejemplo: Plan de Junta_23/01/2019 |  |

**Comment by EricBL3** [comment]
Yo lo veo bien, solo cambiaría la parte de notificación con estos dos puntos:

1.  Creo que sería mejor tener definidas las juntas departamentales de cada semana a más tardar el viernes anterior (como le hicimos esta semana que el viernes quedaron ya definidas las fechas y horarios). La excepción serían las juntas de emergencia aunque también para esas hay que definir muy bien qué cuenta como emergencia y con cuanta anticipación se deben agendar.
2. No se si sea por el idioma en el que cada quien tenga slack pero el comando que yo tengo que escribir para que le llegue a todos un mensaje es @channel. Hay que checar muy bien cuáles son los que acepta slack e incluir todos para que no haya confusión.

**Comment by JoseCarlosPa** [comment]
> Yo lo veo bien, solo cambiaría la parte de notificación con estos dos puntos:
> 
> 1. Creo que sería mejor tener definidas las juntas departamentales de cada semana a más tardar el viernes anterior (como le hicimos esta semana que el viernes quedaron ya definidas las fechas y horarios). La excepción serían las juntas de emergencia aunque también para esas hay que definir muy bien qué cuenta como emergencia y con cuanta anticipación se deben agendar.
> 2. No se si sea por el idioma en el que cada quien tenga slack pero el comando que yo tengo que escribir para que le llegue a todos un mensaje es @channel. Hay que checar muy bien cuáles son los que acepta slack e incluir todos para que no haya confusión.

Se agrego la parte correspondiente a la fecha mínima (viernes posterior a la semana de la junta) , en referencia de "Que es una junta de emergencia" Estaria descrito en el mismo proceso, también se agrego la opción en ingles @channel, de momento no encontré otro comando diferente a @canal o @channel

**Comment by JoseCarlosPa** [comment]
Adjunto el documento con el .md en caso de que quieran editarlo revisarlo localmente 

[Proceso-de-juntas.md](https://github.com/Taro-IT/docs/files/7085796/Proceso-de-juntas.md)

**Comment by angieanaya** [comment]
En general el proceso está bien, pero tengo entendido que la fecha mínima debería de ser el viernes anterior a la junta en lugar de _posterior_.  Por otro lado, creo que sería bueno dividir la minuta entre ejecución y previo a la junta, es decir especificar que campos se llenarán previo a la junta (como agenda de la reunión, tema, fecha, responsable) y cuáles se llenan durante la ejecución de la junta.  
Tengo dos dudas: 
1. ¿En algún momento se define como se seleccionará al autor de la minuta? 
2. ¿La agenda de las juntas departamentales se hará llegar a los participantes por slack o uno se tiene que meter a la minuta para ver esta agenda?

Adjunto el documento .md en el que edité algunos errores de ortografía que había detectado y cambié la palabra _posterior_ por _anterior_.
[Proceso-de-juntas.md](https://github.com/Taro-IT/docs/files/7085874/Proceso-de-juntas.md)

**Comment by AAcostac** [comment]
Se ve adecuado en su mayoría. Me surgen estas preguntas:
- ¿Se debería incluir en esta redacción quien es responsable de agendar las reuniones y de crear el evento en el calendario?
- ¿Se especifica si hay un moderador de la junta durante el paso de ejecución?

También, hay un espacio de mas al inicio en 
> ( Usar la Plantilla para...

aun en la versión de Angie.

**Comment by JoseCarlosPa** [comment]
- ¿En algún momento se define como se seleccionará al autor de la minuta?
R = El autor de la minuta debería ser quien solicite la junta departamental dado que es la persona que tiene la necesidad de expresar un punto o puntos , en dado caso de que sea totalmente general, seria Departamento taro
- ¿La agenda de las juntas departamentales se hará llegar a los participantes por slack o uno se tiene que meter a la minuta para ver esta agenda?
R = mmm posiblemente se pueda dar difusión vía slack, pero no se que tan conveniente sea este punto ya que se puede perder entre los mensajes
- ¿Se debería incluir en esta redacción quien es responsable de agendar las reuniones y de crear el evento en el calendario?
R = No, en este caso este proceso es para que cualquier persona del departamento pueda agendar una junta departamental , en este caso quien lo solicita seria quien lo agendaría y crearía en el calendario, de hecho se esta haciendo una guía para agregar cosas al calendario 
- ¿Se especifica si hay un moderador de la junta durante el paso de ejecución?
R = No actualmente, se podría poner como un punto importante 


En cuestión del espacio y la actualización ya se han  agregado los cambios @angieanaya  @AAcostac

**Comment by karlaromerox3** [comment]
Con las respuestas a las dudas anteriores, me parece que el proceso es adecuado y está bien. 👍🏻LGTM.

**Comment by dinnos** [comment]
Creo que las respuestas anteriores refinan el proceso, solo recuperaría la parte de tener un moderador o alguna persona que sea la que coordine toda la reunion para evitar que se pierda el objetivo de la misma pero como comentan que el que lleva la minuta es el que solicito la junta no sé si este podría ser mejor el moderador y designar a una persona adicional para la minuta.
