### ISSUE TITLE
G01-Guía para Agendar juntas 

### ISSUE THREAD

**Issue by JoseCarlosPa** [Taro-IT/docs#9]

**Comment by JoseCarlosPa** [comment]
**Propuesta para Guía para agendar eventos**

## Objetivo
**Principal:** Orientar en la creación y toma de decisión de fechas de un evento departamental dentro del calendario oficial y recreativo de Taro, esto incluye los calendarios:

<ul><li>Académicos (semestre i)</li><li>Departamentales</li><li>Equipos correspondientes</li></ul>

**Secundario:** Organizar de manera visual y ordenada todos los eventos para mejorar la organización y planeación personal de cada integrante del departamento, permitiendo su mayor participación en todos los eventos.


## Pre-requisitos

Contar con las plantilla:
- Contar con acceso al calendario virtual [Académico (Semestre i)](https://calendar.google.com/calendar/embed?src=itesm.mx_jd61cv3hbbmtuiib93un8s2lok%40group.calendar.google.com&ctz=America%2FMexico_City)
- Contar con acceso al calendario virtual [Departamental](https://calendar.google.com/calendar/embed?src=c_fprk5lfepv1dslipu1dv1let2c%40group.calendar.google.com&ctz=America%2FMexico_City)
- Contar con acceso al calendario virtual por Equipos ( [Smothie](url) o [Expresso](url) )

Nota: _En caso de no contar con acceso a los calendarios se deberá  seguir lo siguientes pasos:, de lo contrario puede pasar a la sección "Norma para los eventos"_

## Pedir acceso al calendario Virtual 
En caso de no contar con acceso al calendario puedes seguir estos pasos para obtener tu acceso

<ol>
<li> Ingresa a Google Calendar: Veras una pantalla parecida a esta

![image](https://user-images.githubusercontent.com/38788518/131545238-6da6e153-9ddd-4e03-a0a8-492f0d860cec.png)


<li>Selecciona el Calendario que deseas compartir, te aparecerá una palomita y el calendario se llenara con los eventos actuales

![image](https://user-images.githubusercontent.com/38788518/131545739-6e2a276e-1b17-4bef-93eb-2d5c794dd2b8.png)



En proceso

**Comment by JoseCarlosPa** [comment]
Adjunto el .md para la edición o importación

[guia.md](https://github.com/Taro-IT/docs/files/7094680/guia.md)

**Comment by EricBL3** [comment]
Yo veo bastante bien la guía. Corregí algunas cosas de ortografía y también de formato del archivo de Markdown. Yo los estoy haciendo en vs code y bajé una extensión que pone warnings si estás violando alguna convención jajaja entonces arreglé las que me parecieron pertinentes. Por si les interesa checarlo la convención es esta: https://github.com/DavidAnson/markdownlint/blob/v0.23.1/doc/Rules.md](url) y si usan vs code la extensión se llama **markdownlint**.

Adjunto el .md.

[guia.md](https://github.com/Taro-IT/docs/files/7095080/guia.md)

**Comment by karlaromerox3** [comment]
Se ve bien, sin embargo me queda la duda de que en los equipos, ¿cómo podríamos saber si el link de Zoom ya está en uso, siendo que no podemos ver el calendario de ellos? ¿Deberíamos preguntar siempre al Team Leader del otro equipo o será que hay otra forma más rápida de saberlo? Propongo que para cada junta/evento de equipo, se genere un link de zoom diferente en la cuenta del dpto, y el link normal se quede para las juntas departamentales. 🤔

Y solo como nota, me parece bien que en la descripción se pongan los puntos a tocar, creo que eso resuelve lo que se veía en el Proceso para Juntas, donde se sugería mandar la agenda por Slack. 👍🏻

**Comment by JoseCarlosPa** [comment]
> Se ve bien, sin embargo me queda la duda de que en los equipos, ¿cómo podríamos saber si el link de Zoom ya está en uso, siendo que no podemos ver el calendario de ellos? ¿Deberíamos preguntar siempre al Team Leader del otro equipo o será que hay otra forma más rápida de saberlo? Propongo que para cada junta/evento de equipo, se genere un link de zoom diferente en la cuenta del dpto, y el link normal se quede para las juntas departamentales. 🤔
> 
> Y solo como nota, me parece bien que en la descripción se pongan los puntos a tocar, creo que eso resuelve lo que se veía en el Proceso para Juntas, donde se sugería mandar la agenda por Slack. 👍🏻

Listo, se generaron dos links fijos para los dos equipos, quedando 3

General
Cinica
Medio Camino

De esta forma se pueden usar a libertad sin que esten uno sobre otro
